-- https://wiki.hypr.land/Configuring/Basics/Autostart/

hl.on("hyprland.start", function () 
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
  hl.exec_cmd("quickshell")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("hyprctl setcursor BreezeX-Dark 28")
  hl.exec_cmd("easyeffects --gapplication-service")
  hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("ollama serve")
  hl.exec_cmd("~/.config/hypr/scripts/update-notify.sh")
  hl.exec_cmd("~/.config/hypr/scripts/random_wall.sh")
  hl.exec_cmd("gsr-ui")

  hl.exec_cmd("kdeconnectd")
  hl.exec_cmd("kdeconnect-indicator")
  hl.exec_cmd("thunar --daemon")
  hl.exec_cmd("sunshine")
  hl.exec_cmd("vesktop --start-minimized")
  hl.exec_cmd("steam -silent")
end)
