hl.exec_cmd("uwsm app -- hyprpm reload")
hl.exec_cmd("uwsm app -- gnome-keyring-daemon --start --components=secrets,pkcs11,ssh")
hl.exec_cmd("uwsm app -- hyprctl setcursor 'Bibata-Modern-Classic' 24")
hl.exec_cmd("uwsm app -- awww-daemon")
hl.exec_cmd("systemctl --user enable --now hypridle.service")
hl.exec_cmd("uwsm app -- quickshell")
hl.exec_cmd("uwsm app -- wl-paste --type text --watch cliphist store")
hl.exec_cmd("uwsm app -- wl-paste --type image --watch cliphist store")
hl.exec_cmd("uwsm app -- fcitx5 -d")
hl.exec_cmd("uwsm app -- sunshine")
hl.exec_cmd("python ~/.config/hypr/scripts/click_shrink.py")
hl.exec_cmd("~/.config/hypr/scripts/update-notify.sh")
hl.exec_cmd("~/.config/hypr/scripts/random_wall.sh")

hl.exec_cmd("kdeconnectd")
hl.exec_cmd("kdeconnect-indicator")
hl.exec_cmd("thunar --daemon")
